### ISSUE TITLE
Building an amazing people and culture team at Stitch Fix!!!

### ISSUE THREAD

**Issue by Margowheel** [github/hr-opensource#11]
Hello
I've got some very juicy People and Culture leadership roles on my team. I'm going to leverage this forum to share them with this great community - thanks for the idea KD . Please reach out to me with any candidates. You can reach me directly at mwheeler@stitchfix.com

Thanks for your support!

**Comment by kellidrag** [comment]
closing - @Margowheel hired all these roles WOOT! :boom:
