### ISSUE TITLE
Stitch Fix - Director Training and Leadership Development Opportunity

### ISSUE THREAD

**Issue by Margowheel** [github/hr-opensource#12]
Stitch Fix is a beautiful blend of the art and science that mirrors the incredible personalized experience we deliver to our clients. The People and Culture team is committed to creating a fulfilling and inspiring place to work for all of the people who deliver that client experience - from our warehouse team to tech talent to merchants to stylists. We pride ourselves on creating a fun and collaborative environment where we solve problems together. We are looking for smart, kind and goal oriented people to join our team. 
The Role
Reporting into the Chief People Officer (CPO), the Director, Training + Leadership  Development will be responsible for ensuring our people’s potential is maximized. From leadership coaching to remote workforce development and performance, this role will have a large breadth of responsibility. You may consider it to be the Jack or Jill of all People Development trades! And the vast scope with a high growth, people-centric organization is what will probably draw you to be interested in a role like this. 

Responsibilities

You will be provide strategic assessment and recommendations to the CPO for a comprehensive people development plan.
You will be responsible for management coaching, leadership  and professional development across the organization, at every level.
You will partner with the Styling and Product leadership teams to plan and execute field training programs for all remote employees. Creating a robust strategy will be a game-changer to this group and one you will be very proud of!
You will consult with the leaders to assess and analyze the learning needs of employees based on current and future strategic plans. 
You will be responsible for various learning platforms: from smaller group trainings/ leadership forums to e-learning platforms and online tools.
You will facilitate talent calibration, succession management and high-potential employee programs.
You will have the honour and responsibility of ensuring that training and development is delivered in an inspiring and culturally relevant manner.
Your impact of developing leaders will create ripples beyond the organization and through our client experience. (We believe that to be a great responsibility!)

Requirements
8+ years of progressive experience in leadership HR roles within a high growth environment
Strong people developer with a flexible leadership style to adapt to various learning methodologies
Able to scale systems and processes in a high-growth, high-change environment.
Has demonstrated the ability to balance strategic thinking with detailed, focused execution.
Possesses the professional, interpersonal, and cultural skills to establish early and lasting trust, credibility, and rapport at all levels of the organization.

**Comment by kellidrag** [comment]
closing - @Margowheel hired all these roles WOOT! :boom:
