### ISSUE TITLE
Stitch Fix Opportunity - Director Talent Acquisition

### ISSUE THREAD

**Issue by Margowheel** [github/hr-opensource#13]
Stitch Fix is a beautiful blend of the art and science that mirrors the incredible personalized experience we deliver to our clients. The People and Culture team is committed to creating a fulfilling and inspiring place to work for all of the people who deliver that client experience - from our warehouse team to tech talent to merchants to stylists. We pride ourselves on creating a fun and collaborative environment where we solve problems together. We are looking for smart, kind and goal oriented people to join our team. 
The Role
The Talent Acquisition Leader  will build the foundation for attracting the very best talent to Stitch Fix. You will develop innovative solutions and partner directly with the Chief People Officer (CPO) to create a hiring roadmap. This is a strategic role charged with leading hiring for technical and non-technical teams across the entire organization. We are targeting someone with both tech and non-tech recruiting and management experience ideally within a technology company. This role is a true game changer and your contribution will be critical as we embark upon our high growth phase. 
Responsibilities
You will work closely with the CPO to develop and drive talent acquisition and employer branding strategies.
You will prioritize recruiting resources.
You are responsible for optimizing hiring manager and candidate experience during the interview process.
You will create the systems, processes and reports to support the overall effectiveness of the recruitment strategy. 
You may be required to recruit for senior level/ business critical roles.
Requirements
7+ years of experience in recruiting/ recruiting management within the technology space.
Strong track record of effectively managing recruiting teams, experience developing and mentoring employees to maximize team performance.
Partner with hiring managers to understand positions and team needs.
Experience working with recruiting tools and systems, including: applicant tracking systems, resume databases, internet sourcing tools, social media strategies, etc.
Creatively source candidates from relevant networks, online and internal databases, employee referrals and passive candidates through networking and research.
Demonstrated organizational skills, with a keen focus on delivering business results in an open and collaborative environment. 
Excellent communication skills, both written and oral.

**Comment by kellidrag** [comment]
closing - @Margowheel hired all these roles WOOT! :boom
