### ISSUE TITLE
Stitch Fix Opportunity - People and Culture Business Partner

### ISSUE THREAD

**Issue by Margowheel** [github/hr-opensource#14]
People and Culture 
Stitch Fix Culture is a beautiful blend of the Art and Science that mirrors the incredible personalized experience we deliver to our clients. The People and Culture team is committed to creating a fulfilling and inspiring place to work for all of the people who deliver that client experience - from our warehouse team to tech talent to merchants to stylists. We pride ourselves on creating a fun and collaborative environment where we solve problems together. We are looking for smart, kind and goal oriented people and culture leaders to join our team. 
your unique impact at Stitch Fix:
You partner with our business leaders to ensure their strategic goals have the people power in place to make them a reality.  This role encompasses a broad group of clients at our Headquarters and Warehouse, including our Merchandise and the Technology team. You will manage a People and Culture business partner associate who will be onsite at the Warehouse.
You are a trusted advisor who takes a full view of people strategies from attracting to development to total rewards. You share those needs proactively with our People Functional leaders in order to create innovative solutions.
You make it happen by implementing People and Culture strategies and initiatives.
You are the coach in supporting our leaders as they work through the many scenarios that come up when managing people.  You develop leaders who have strong people management skills.

Required Skills, Experience and Academic/Educational Requirements:
•	Bachelor or certificate in Human Resources Management.
•	Minimum 5 years working experience in a human resources capacity.
•	Proven ability to build strong working relationships with senior level leaders.
•	A flexible team player with a proven ability to work successfully in a collaborative environment.
•	Thorough understanding of Employment Practices.

**Comment by kellidrag** [comment]
closing - @Margowheel hired all these roles WOOT! :boom

**Comment by Margowheel** [comment]
Whee!!!!
