### ISSUE TITLE
BrightWomen and Spark Film Event -- August 13 -- Open to the public

### ISSUE THREAD

**Issue by bsteinbe** [github/hr-opensource#20]
BrightWomen is proud to partner with Spark, a philanthropic network of young professionals who invest to improve the lives of women around the world, to present the film screening of WADJDA. 

WADJA is the first feature film shot entirely in Saudi Arabia by a female Saudi filmmaker, and it depicts the story of a young girl determined to raise enough money to buy a bike in a society that sees bicycles as dangerous to a girl's virtue. In a country where cinemas are banned and women cannot drive or vote, writer-director Haifaa Al Mansour is breaking barriers with her new film.
 
After the film, we will hold a Q/A with Esther Pearlman, Founder of Camp Reel Stories, a one-week media camp for girls who want to learn how to make movies in the new digital media era. We will discuss the barriers to women in film industry and what Camp Reel Stories is doing to empower the next generation of women filmmakers.

Your ticket sale donation of $15 will help Spark and its programs. To RSVP: 

http://bit.ly/BRWADJDA

Please invite your friends and help us promote this on social media: 

Join #BrightWomen & @sparksf on 8/13 at 6pm for the screening of @WadjdaFilm feat. guest speaker @lotusmadre http://ow.ly/zNYZ7 #BGood

**Comment by kellidrag** [comment]
Closing from Aug @bsteinbe :+1:
