### ISSUE TITLE
Sara Sperling - HR Leader

### ISSUE THREAD

**Issue by kellidrag** [github/hr-opensource#30]
I wanted to send this note to connect you all to Sara Sperling. Good friend and colleague of mine (we worked at Y! together) and since then she has had a great run at Facebook as their Diversity & Inclusion Lead and then moved down to Santa Monica to run HR for SnapChat.

She has a little girl up here who is in Kindergarten and recently made the decision that she just could not be in So Cal away from her and is in process of moving back to the Bay Area and will be wrapping up with SnapChat soon.

She is looking to network and connect with great people and take her time talking to various awesome companies to ultimately make the right next step. I told her what better group to introduce her to than this one. If you all have time to connect with her at any time and shoot her some ideas that would be awesome! Please feel free to connect directly below. 

Sesperling@yahoo.com

Thanks!

**Comment by Pmccord** [comment]
Not to mention that Snapchat is a madhouse! Remind me to tell you my Evan Siegal story sometime. I know a company, Vessel, here in town looking for someone now. Have her contact me.

Patty

**Comment by kellidrag** [comment]
:laughing:

**Comment by kellidrag** [comment]
closing for now... :+1:
