### ISSUE TITLE
Looking for a VP of Sales to join Swipely

### ISSUE THREAD

**Issue by AlainaRestivo** [github/hr-opensource#35]
Hi,

We are looking for a new dynamic VP of Sales to join Swipely.  Swipely helps restaurants and other local merchants make smarter decisions, grow profits and understand customers. With data from instore systems, payments and the social web, Swipely makes it easy to understand what brings customers back. Merchants now use Swipely to manage over 4 billion dollars in annual sales, up more than 300%
over the last year.

Fantastic company, with great potential.  Our ideal would be someone who has experience selling to local businesses.  Do you know someone looking, or have a lead?  Please PM me and I can share more!  We're looking to move fast.  The ideal would be a proven executive with experience leading and managing B2B SaaS Sales, ideally to SMBs, in a high-growth technology organization. Expertise
selling to full service restaurants and merchants is a plus.

**Comment by kellidrag** [comment]
@pastjohn if our VP of Sales here, I will ask him if he knows anyone great thanks!

**Comment by pastjohn** [comment]
@AlainaRestivo @kellidrag I may have someone actually. Can you call me: +1 650 504 1945. I'm on a plane Monday at 12 Noon ....before could work or after 4P pst.
